<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <AssemblyName>ItemsReport</AssemblyName>
    <RootNamespace>ItemsReport</RootNamespace>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.2.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CommonCode\CommonCode.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ItemReportScript.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="PAT.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <TypeScriptCompile Update="Scripts\**\*.ts">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </TypeScriptCompile>
  </ItemGroup>
  <PropertyGroup>
    <TypeScriptSourceMap>false</TypeScriptSourceMap>
    <TypeScriptOutFile>ItemReportScript.js</TypeScriptOutFile>
    <TypeScriptTarget>ES6</TypeScriptTarget>
  </PropertyGroup>
</Project>